sudo: required
services:
  - docker

before_install:
  - docker build -t frankbruno/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true frankbruno/react-test npm test -- --coverage --watchAll=false

after_success:
  - docker build -t frankbruno/multi-client ./client
  - docker build -t frankbruno/multi-nginx ./nginx
  - docker build -t frankbruno/multi-server ./server
  - docker build -t frankbruno/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push frankbruno/multi-client
  - docker push frankbruno/multi-nginx
  - docker push frankbruno/multi-server 
  - docker push frankbruno/multi-worker